default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task4_development
  host: localhost
  username: postgres
  password: MyPassword

test:
  <<: *default
  database: task4_test

production:
  <<: *default
  database: task4_production
  username: postgres
  password: <%= ENV["TASK4_DATABASE_PASSWORD"] %>
